#!/bin/sh -x

# bootstrap - create files in the "auto" tool-chain
#
# Copyright 2018 Kavalogic, Inc.
#
# This file is part of Tovero.
#
# Tovero is free software; you can redistribute it and/or modify it
# under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# Tovero is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
# General Public License for more details.  You should have received a
# copy of the GNU General Public License along with Tovero. If not,
# see <http://www.gnu.org/licenses/>.

# install libtool support files
libtoolize

# create aclocal.m4
aclocal -I m4
# create config.in.h
autoheader
# create makefile.in for top level and subdirectories
# (-Woverride flag is to catch user redefinitions of automake rules/variables)
automake --add-missing -Woverride -Werror
# creates configure script
autoconf

# Notes:
# -----
# Other "auto" tools:
#
# autoreconf - remake build system files
# autoscan - used to create a starter configure.ac or validates existing one
# -----
# autoconf --trace - scans configure.ac
# -----
